name: TestSuite

on: [push, pull_request]

jobs:
  testing-ubuntu:
    name: TestSuite on Ubuntu-20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Set up Conda
        uses: s-weigand/setup-conda@v1.0.5
      - run: conda --version
      - run: which python

      - name: Setup Conda Environment
        run: |
          conda create --prefix $HOME/test_env -c conda-forge --yes --quiet python=3.8 pip pytest
          source activate $HOME/test_env   
          conda install --quiet --yes -c conda-forge pytest cython sympy future pyparsing numpy jinja2 six scipy sphinx gsl coverage
          pip install .   
          coverage run --rcfile=/home/runner/work/brian2/.coveragerc /home/runner/work/brian2/dev/continuous-integration/run_test_suite.py
      # - name: Run tests
      #   run: | 
      #     SOURCE_PATH=$(pwd)
      #     pwd
      #     cd ..
      #   env:
      #     script_name: /home/runner/work/brian2/brian2/dev/continuous-integration/run_test_suite.py
      #     AGENT_OS: ${{runner.os}}
